### ISSUE TITLE
json format

### ISSUE THREAD

**Issue by kaptinlin** [agoda-com/otelzap#2]
Can it collect log with json format?

**Comment by chameleon82** [comment]
I believe you referring to  [OTEL_EXPORTER_OTLP_PROTOCOL=http/json](https://opentelemetry.io/docs/concepts/sdk-configuration/otlp-exporter-configuration/#otel_exporter_otlp_protocol) option. Currently this option is not yet supported in the [otlplogshttp/client](https://github.com/agoda-com/opentelemetry-logs-go/blob/master/exporters/otlp/otlplogs/otlplogshttp/client.go#L259)

**Comment by kaptinlin** [comment]
any plan support it?

**Comment by chameleon82** [comment]
please follow this PR
https://github.com/agoda-com/opentelemetry-logs-go/pull/5

**Comment by chameleon82** [comment]
Hi @KaptinLin ,

With [latest release](https://github.com/chameleon82/opentelemetry-logs-go/tree/master/exporters#otel-client-with-httpjson) you have 2 options to configure it:

Use `OTEL_EXPORTER_OTLP_PROTOCOL=http/json` env configuration 

```
func main() {
	ctx := context.Background()
	exporter, _ := otlplogs.NewExporter(ctx) // will create exporter with http client `http/protobuf` protocol by default

}
```

or specify http client with json protocol explicitly:

```
client := otlplogshttp.NewClient(otlplogshttp.WithJsonProtocol())
exporter, _ := otlplogs.NewExporter(ctx, otlplogs.WithClient(client))
```

**Comment by kaptinlin** [comment]
Thank you very much!
